bikehub/bikehub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    # path('cart/', include('cart.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bikehub/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('bike/<int:id>', views.bike_view, name='bike_view'),
    path('add_to_cart/<int:id>/delete', views.bike_delete, name='bike_delete'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('search', views.search, name='search'),
    path('ratings', views.ratings, name='ratings')


]

bikehub/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about,  name='about'),
    path('blog/', views.blog, name='blog'),
    path('shop/', views.shop, name='shop'),

]

bikehub/cart/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


# Create your models here.


class Bike(models.Model):
    name = models.CharField(default="new bike", max_length=150)
    image = models.ImageField(upload_to='cart/',
                              default='', blank=True, null=True)
    price = models.FloatField(default=0.0)
    date = models.DateTimeField(blank=True, null=True)
    # content = models.TextField(max_length=250)
    content = RichTextUploadingField(default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cart:bike_view", kwargs={"id": self.id})


class Cart(models.Model):
    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, )

    def ___str__(self):
        return self.user_id


class CartItem(models.Model):
    bike_id = models.ForeignKey(Bike, on_delete=models.CASCADE, default=None)
    cart_id = models.ForeignKey(Cart, on_delete=models.CASCADE, default=None)
    quantity = models.PositiveIntegerField()
    price = models.FloatField(default=0.0)

    def __str__(self):
        return self.cart_id


STATUS_CHOICES = (
    ("Started", "Started"),
    ("Abandoned", "Abandoned"),
    ("Finished", "Finished")
)


class Order(models.Model):

    bike_id = models.ForeignKey(
        Bike, on_delete=models.CASCADE, default=None)
    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,  on_delete=models.CASCADE)
    # date = models.DateTimeField(auto_now=True, auto_now_add=False)
    status = models.TextField(
        max_length=120, choices=STATUS_CHOICES, null=True)
    first_name = models.CharField(max_length=120, default="nitesh")
    last_name = models.CharField(max_length=120, default="pantha")
    email = models.EmailField("email", max_length=250,
                              default="niteshraz619@gmail.com")
    address = models.CharField(
        max_length=250, default="Bhaktapur-5 , Ghattaghar")
    city = models.CharField(max_length=120, default="Bhaktapur")
    payment_method = models.CharField(
        max_length=250, default="Cash On Delivery")

    def __str__(self):
        return self.bike_id


class OrderItem(models.Model):
    bike_id = models.ForeignKey(
        CartItem, on_delete=models.CASCADE, default=None)
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE, default=None)
    quantity = models.PositiveIntegerField()
    price = models.FloatField(default=0.0)

    def __str__(self):
        return self.order_id

bikehub/cart/forms.py
from django import forms

from .models import CartItem


class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        # fields = ['bike_id', 'cart_id', 'quantity', 'price']
        fields = ['bike_id']


class OrderItemForm(forms.ModelForm):
    class Meta:
        fields = ['bike_id', 'order_id', 'quantity', 'price']

bikehub/cart/views.py
from django.shortcuts import render, get_object_or_404
import time
# from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.models import User, auth

from django.urls import reverse
from django.http import HttpResponse
from .forms import CartItemForm, OrderItemForm
from django.contrib import messages
from cart.models import Bike, Cart, Order, CartItem
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.utils import timezone
from django.db.models import FloatField
from django.db.models import Count
from django.shortcuts import redirect
from django.db.models import Q

# Create your views here.


def bike_view(request, id=None):
    bike = Bike.objects.get(id=id)
    context = {
        'bike': bike
    }
    return render(request, 'cart/bike.html', context)


@login_required(login_url='/admin/login/')
def add_to_cart(request):
    carts = CartItem.objects.all()
    total = 0
    bike_ids = []
    bike_id = None
    user = request.user
    cart = Cart.objects.get(user_id=user.id)
    for each in carts:
        bike_ids.append(each.bike_id.id)
        indvidual_price = each.bike_id.price * each.quantity
        total += indvidual_price
        print(bike_ids)
    if request.method == 'POST':
        form = CartItemForm(request.POST)
        # form.data['cart_id'] = cart.id
        print(form.data)
        if form.is_valid():
            print("form valid")
            # print(form.data)
            form.save(commit=False)
            form.user = request.user
            form.date = timezone.now()
            form.cart_id = cart.id
            bike_id = form.data['bike_id']
            bike = Bike.objects.get(id=bike_id)
            bike_id = int(bike_id)

            if bike_id in bike_ids:
                # bike_id = request.POST.get('bike_id')
                c1 = CartItem.objects.get(bike_id=bike_id)
                c1.quantity += 1
                c1.save()
                messages.success(
                    request, 'You have successfully added your items in cartbox')
            else:
                c1 = CartItem.objects.create(
                    bike_id=bike,
                    quantity=1,
                    cart_id=cart,
                    price=bike.price
                )
        else:
            messages.error(
                request, 'Error adding items in cartbox')

    context = {
        "carts": carts,
        "total": total,
        "bike_id": bike_id,

    }
    return render(request, 'cart/add_to_cart.html', context)


def bike_delete(request, id=None):
    obj = get_object_or_404(CartItem, id=id)
    print(obj.id)
    obj.delete()

    return redirect('/cart/add_to_cart/')


def search(request):
    if request.method == 'POST':
        srch = request.POST['srh']

        if srch:
            match = Bike.objects.filter(Q(name__icontains=srch) |
                                        (Q(price__icontains=srch))
                                        )
            if match:
                return render(request, 'cart/search.html', {'sr': match})
            else:
                messages.error(request, 'no result found')
        else:
            return redirect('cart/search/')
    return render(request, 'cart/search.html')


def checkout(request):

    if request.method == 'POST':
        form = OrderItemForm(request.POST)
        form.data['order_id'] = order.id

        cart = Cart.objects.get(id=user_id)
        if user_id in user_id:
            c1 = CartItem.objects.all()
            c2 = OrderItem.objects.all()
            c2 = c1.copy()
            c1.delete()
            if c2 in c2:
                c3 = OrderItem.objects.get(id=order_id)
                c4 = Order.objects.create()
                c4 = c3.copy()
                c4.save()
                first_name = request.POST['first_name']
                last_name = request.POST['last_name']
                email = request.POST['email']
                address = request.POST['address']
                city = request.POST['city']
                user = auth.authenticate(first_name=first_name,
                                         last_name=last_name, email=email)
                if user.is_authenticated:
                    print('You have successfully make a checkout.')
                    return render(request, 'cart/ratings.html')
                else:
                    redirect('/cart/checkout/')
        else:
            return redirect("/cart/add_to_cart")
    return render(request, 'cart/checkout.html')
    # if request.method == 'POST':
    #     form = OrderItemForm(request.POST)
    #     cart = Cart.objects.get(id=user_id)
    #     if user_id in user_id:
    #         c1 = CartItem.objects.all()
    #         # form = c1.copy()

    #         form.save()
    #         if form.is_valid():
    #             print(form.data)
    #             c1.delete()
    #             c2 = OrderItem.objects.get(id=order_id)
    #             c2 = form.copy()
    #             c2.save()
    #             if order_id in order_id:
    #                 c3 = Order.objects.all()
    #                 c3.save()
    #                 first_name = request.POST['first_name']
    #                 last_name = request.POST['last_name']
    #                 email = request.POST['email']
    #                 address = request.POST['address']
    #                 city = request.POST['city']
    #                 user = auth.authenticate(first_name=first_name,
    #                                          last_name=last_name, email=email)
    #                 if user.is_authenticated:
    #                     print('You have successfully make a checkout.')
    #                     return render(request, 'cart/ratings.html')
    #                 else:
    #                     redirect('/cart/checkout/')
    #     return HttpResponse('Error submiting form')


def ratings(request):
    return render(request, 'cart/ratings.html')


# if request.method == 'POST':
    #     first_name = request.POST['first_name']
    #     last_name = request.POST['last_name']
    #     email = request.POST['email']
    #     address = request.POST['address']
    #     city = request.POST['city']
    #     user = auth.authenticate(first_name=first_name,
    #                              last_name=last_name, email=email)
    #     if user.is_authenticated:
    #         if user.is_active:
    #             return redirect('/ratings/')
    #         else:
    #             return HttpResponse('You dont have an account with us')

    # form = CartItemForm(request.POST)
    # forms = OrderItemForm(request.POST)
    # if form.is_valid():
    # form.save()
    #     forms.save()
    #     print(form.data)
    #     print(forms.data)
    #     user = request.user
    #     cart = Cart.objects.get(user_id=user.id)
    #     if user_id in user_id:
    #         carts = CartItem.objects.all()
    #         order = OrderItem.objects.all()
    #         if order in order:
    #             c1 = carts.copy()
    #             c2 = c1.save()

    #             new_order, created = order.objects.get_or_create(
    #                 order=order)
    #             if created:
    #                 new_order.order_id = str(time.time())
    #                 new_order.save()
    #             if new_order.status == "Finished":
    #                 cart.delete()
    #                 c3 = new_order
    #                 c3 = new_order.copy()
    # return render(request, 'cart/checkout.html')

bikehub/templates/cart/add_to_cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col">
            <table class="table table-dark ">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Items</th>
                        <th>Qty</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart in carts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cart.bike_id}}
                            <form action="" method="POST">
                                {% csrf_token %}
                                <h3>{{cart.object}}</h3>
                                <a href="{% url 'cart:bike_delete' cart.id %}">Remove</a></td>

                        </form>
                        <td>{{cart.quantity}}
                            <a href="">Edit</a>
                        </td>
                        <td>{{cart.bike_id.price}}</td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <th colspan="3">Order TOtal:</th>
                        <th colspan="5">{{total}}</th>
                    </tr>
                    <tr>
                        <th><button class="btn btn-info"><a href="{% url 'home:index' %}" class="">Continue
                                    Shopping</a></button>
                        </th>
                        <th><button class="btn btn-warning"><a href="{% url 'cart:checkout' %}">Proceed to
                                    Checkout</a></button>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/bike.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <img src="{{bike.image.url}}" alt="{{bike.name}}" class="imagehere">
        </div>
        <div class="col">
            <form action="{% url 'cart:add_to_cart' %}" method="POST">
                {% csrf_token %}
                <button class=" btn btn-secondary" id="name" value="{{bike.id}}" name="bike_id" type="submit"><a href=""
                        class="sobit">Add
                        to
                        cart</a></button>
            </form>
        </div>
    </div>
</div>


<div>
    <p class="suzzan">{{bike.name}}</p>

</div>
<div>
    {{bike.content}}
</div>
<div>
    <p class="suzzan">REVIEW</p>
</div>
</div>
{% endblock %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}




{% csrf_token %}
<div class="container mt-5">
    <div class="row">
        <div class="col">
            <table class="table table-dark ">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Items</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for carts in carts %}
                    <tr>
                        <td>{{forloop.count}}</td>
                        <td>{{cart.bike_id}}</td>
                        <td>{{cart.price}}</td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <th colspan="3">Order TOtal:</th>
                        <th>{{x.price}}</th>
                    </tr>
                    <tr>
                        <th><button class="btn btn-info"><a href="{% url 'home:index' %}" class="">Continue
                                    Shopping</a></button>
                        </th>
                        <th><button class="btn btn-warning"><a href="{% url 'cart:checkout' %}">Proceed to
                                    Checkout</a></button>
                        </th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>


{% endblock content %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/checkout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block title %}
About us
{% endblock %}


{% block content %}

<div class="container mt-5">
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Billing Address</h1>
        <form action="/checkout/" method="POST">
            <form class="needs-validation" novalidate>
                <div class="form-row">
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip01">First name</label>
                        <input type="text" class="form-control" id="validationTooltip01" placeholder="First name"
                            value="{{first_name}}" required name="first_name">
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip02">Last name</label>
                        <input type="text" class="form-control" id="validationTooltip02" placeholder="Last name"
                            value="{{last_name}}" required name="last_name">
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>

                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputEmail4">Email</label>
                        <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email"
                            value="{{email}}">
                    </div>

                </div>
                <div class="form-group">
                    <label for="inputAddress">Address</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="Chardobato-5 , Bhaktapur"
                        name="address" value="address">
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input type="text" class="form-control" id="inputCity" name="city" value="city">
                    </div>

                </div>
                <hr>
                <h4>Payment</h4>
                <form action="/cart/checkout/">
                    <input type="radio" name="gender" value="debit">Cash On Delivery <br>
                    <!-- <input type="radio" name="gender" value="esewa"> Khalti<br> -->

                </form>
                <a href="{% url 'cart:ratings' %}"><button type="submit" class="btn btn-primary btn-block  ">Continue to
                        checkout</button></a>
            </form>
    </div>
</div>
{% endblock  %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/index.html
{% extends 'base.html' %}
{% load fontawesome %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block title %}
{{instance.title}}
{% endblock %}

{% block content %}

<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/duke.jpg' %}" class="d-block w-100 fixed-height" alt="">
                <div class="overlay"></div>

                <div class="carousel-caption d-none d-md-block ">
                    <h5>DUKE 390</h5>
                    <p>Magnificient pickup and smooth with good mobility.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/bullet.jpg' %}" class="d-block w-100 fixed-height" alt="">
                <div class="overlay"></div>
                <div class="carousel-caption d-none d-md-block ">
                    <h5>Royal Enfield</h5>
                    <p>Royal Enfield is a beast. </p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/apache.jpg' %}" class="d-block w-100 fixed-height" alt="">
                <div class="overlay"></div>
                <div class="carousel-caption d-none d-md-block">
                    <h5>Apache 390</h5>
                    <p>Best racing bikes rightnow.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<div class="container mt-4">
    <div class="row">
        {% for bike in bike %}
        <div class="col-sm-6 col-sm-offset-3">
            <div class="bike">
                <div>
                    <img src="{{bike.image.url}}" alt="{{bike.name}}" class="myimage">
                </div>
                <div class="card-body">
                    Name:{{bike.name}}<br>
                    Price:{{bike.price}}<br>
                    <button class="btn btn-secondary" id="name" value="{{bike.id}}" name="bike_id" type="submit"><a
                            href="{% url 'cart:bike_view' %}" class="sobit">View-Detail</a></button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/ratings.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block title %}
About us
{% endblock %}


{% block content %}

<div class="container">
    <h1>Thanks for buying our product. Continue shopping </h1>
    <h3>Please give us a rating</h3>
    <div class="rating">
        <input type="radio" name="star" id="star1"><label for="star1"></label>
        <input type="radio" name="star" id="star2"><label for="star2"></label>
        <input type="radio" name="star" id="star3"><label for="star3"></label>
        <input type="radio" name="star" id="star4"><label for="star4"></label>
        <input type="radio" name="star" id="star5"><label for="star5"></label>
    </div>
</div>


{% endblock %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/cart/search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}


<div class="container mt-5">
    <h1>Search Bike related information</h1>
    <form action="{% url 'cart:search' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-lg-5">
                <input type="text" name="srh" class="form-control" placeholder="Enter your bike name / bike price">
            </div>
            <label class="col-lg-2">
                <button type="submit" class="btn btn-secondary btn-block">Search</button>
            </label>

        </div>


    </form>
</div>
<br>
<div>
    {% if messages %}
    <ul class="messages">
        {% for k in messages %}
        <li style="color:red">{{k}}</li>
        {% endfor %}

    </ul>

    {% endif %}
</div><br>


{% if sr %}
{% for k in  sr %}
<div class="container-5">
    <div class="row">
        <div class="col-sm-6">

            {{k}}.{{bike.image.url}}<br>
            Name:{{k.name}}<br>
            price:{{k.price}}<br>
            {{k.content}}
        </div>
        <div class="col-sm-6">
            <a href="{% url 'cart:add_to_cart' %}" method="POST"><button class="btn btn-primary">Add to
                    Cart</button></a>
        </div>

    </div>
</div>

{% endfor %}
{% endif %}







{% endblock content %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}