bikehub/bikehub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    # path('cart/', include('cart.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bikehub/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('bike/<int:id>', views.bike_view, name='bike_view'),
    path('add_to_cart/<int:id>/delete', views.bike_delete, name='bike_delete'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('search', views.search, name='search'),
    path('ratings', views.ratings, name='ratings')


]

bikehub/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about,  name='about'),
    path('blog/', views.blog, name='blog'),
    path('shop/', views.shop, name='shop'),

]

bikehub/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block meta_links%}

    {% endblock %}
    <!-- template tags-->
    {% load static %}
    {% load fontawesome %}
    {% fontawesome_stylesheet %}

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block style_links %}

    {% endblock %}
</head>

<body>
    <!-- place header component here-->
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <!-- Brand-->
        <a class="navbar-brand" href="{% url 'home:index' %}">BikeHub</a>

        <!-- toggler//collapsible Button-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Links-->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:index' %}">home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:shop' %}">shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:blog' %}">Blog</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:contact' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'cart:search' %}" class="nav-link"><i class="fas fa-search"></i></a>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle user-dropdown" type="button"
                            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <a href="#" class="nav-link"><i class="fa fa-user"></i></a>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                            {% if user.is_authenticated %}
                            <!-- <li>Hello , {{user.first_name}}</li> -->
                            <a class="dropdown-item" href="accounts/logout"><i class="fas fa-sign-out-alt"></i>
                                logout</a>
                            {% else %}
                            <a class="dropdown-item" href="accounts/register"><i class="fa fa-user"></i>
                                Register</a>
                            <a class="dropdown-item" href="accounts/login"><i class="fas fa-sign-in-alt"></i>
                                Log In</a>
                            {% endif %}
                            <a class="dropdown-item" href="cart/checkout"><i class="fas fa-check-circle"></i>
                                Checkout</a>
                        </div>
                    </div>
                </li>


                <li class="nav-item">
                    <a href="{% url 'cart:add_to_cart' %}" class="nav-link"><i class="fas fa-cart-plus"></i></a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- this place is for other templates-->
    {% block content %}


    {% endblock %}
    <!-- place footer component here -->
    <footer id="footer">
        <div class="container mt-5">
            <div class="row">
                <div class="col">
                    <p class="suzzan">BIKEHUB</p>
                    <p>BikeHub really emphasizes to latest innnovatives on moterbikes and let clients check the required
                        moterbikes and bike them convienently.
                        .</p>
                    <a href=""><i class="fas fa-phone"></i> +977 9863034659</a><br>
                    <a href=""><i class="fas fa-map-marker-alt"></i>Ghattaghar-Bhaktapur, Nepal.</a><br>
                    <a href=""><i class="fas fa-inbox"></i> bikehubnepal@gmail.com</a>
                </div>

                <div class="col">
                    <p class="suzzan">About Us</p>
                    <p>About Us</p>
                    <p>Contact Us</p>
                    <p>Blog</p>
                    <p>Older History</p>
                    <p>Terms & Conditons</p>

                </div>
                <div class="col">
                    <p class="suzzan">customer services</p>
                    <p>shipping policy</p>
                    <p>compensation first</p>
                    <p>Delivery Information</p>
                    <p>F.A.Qs</p>
                    <p>careers</p>
                </div>
                <div class="col">
                    <p class="suzzan">NEWSLETTER</p>
                    <form class="form-inline">
                        <div class="form-group">
                            <label for="exampleInputEmail1"></label>
                            <input type="email" class="form-control" id="exampleInputEmail1"
                                aria-describedby="emailHelp" placeholder="Enter email">
                            <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with
                                    anyone else.</small> -->
                            <button type="submit" class="btn btn-warning">Subscribe</button>
                        </div>


                    </form>
                    <p>Sign up get 20% sale off for first time, Get all the latest deals and special offers, first.
                    </p>
                    Follow Us:
                    <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
                    <a href="https://www.twitter.com/"> <i class="fab fa-twitter"></i></a>
                    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </footer>


    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
        </script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

{% block script_links %}
{% endblock %}
{% block scripts %}

{% endblock %}