bikehub/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),

]

bikehub/bikehub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
    # path('cart/', include('cart.urls')),
    path('cart/', include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bikehub/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('bike/<int:id>', views.bike_view, name='bike_view'),
    path('add_to_cart/<int:id>/delete', views.bike_delete, name='bike_delete'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('search', views.search, name='search'),
    path('ratings', views.ratings, name='ratings')


]

bikehub/accounts/models.py
from django.db import models

# Create your models here.

bikehub/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages


# Create your views here.


def register(request):

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists.')
                return redirect('register')

            elif User.objects.filter(email=email).exists():
                messages.error(request, 'Email address already exists.')
                return redirect('register')

            else:
                user = User.objects.create_user(
                    username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user.save()
                print('user created')
                return redirect('login')
        else:
            print('password not matching')
            return redirect('register')

        return redirect('/')
    else:
        return render(request, 'accounts/register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.error(request, 'invalid credentials.')
            return redirect("login")
    else:

        return render(request, 'accounts/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

bikehub/templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}




<div class="container mt-5">

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label for="exampleInputText">Username</label>
            <input type="text" class="form-control" id="exampleInputText" placeholder="Enter Username" name="username">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword" placeholder=" Enter Password"
                name="password">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Logged me In</label>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
    </form>
    <h6><a href="{% url 'accounts:register' %}">No account?Create one here.</a></h6>
    <div>
        {% for message in messages %}
        <h4> {{message}} </h4>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}

bikehub/templates/accounts/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links%}

{% endblock %}

{% block content %}

<div class="container mt-5">
    <h1>Create account here.</h1>
    <h6>insert your account information</h6>
    <form action="register">
        <input type="radio" name="gender" value="male"> male
        <input type="radio" name="gender" value="female"> female
        <input type="radio" name="gender" value="other"> Other
    </form>
    <form action="{% url 'accounts:register' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputText">First Name</label>
            <input type="text" class="form-control" id="exampleInputText" aria-describedby="emailHelp"
                placeholder="Enter First Name" name="first_name">
            <small id="emailHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group">
            <label for="exampleInputText">Last Name</label>
            <input type="text" class="form-control" id="exampleInputText" aria-describedby="emailHelp"
                placeholder="Enter Last Name" name="last_name">
            <small id="emailHelp" class="form-text text-muted"></small>
        </div>
        <div class="form-group">
            <label for="exampleInputText">Username</label>
            <input type="text" class="form-control" id="exampleInputText" aria-describedby="emailHelp"
                placeholder="Enter Username" name="username">
            <small id="emailHelp" class="form-text text-muted"></small>
        </div>

        <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                placeholder="Enter email" name="email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                else.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password1</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                name="password1">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword2">Password2</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Confirm Password"
                name="password2">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Keep me logged in.</label>
        </div>

        <button type="submit" class="btn btn-success btn-block">Register</button>
    </form>
    <div>
        {% for message in messages %}
        <h4> {{message}} </h4>
        {% endfor %}
    </div>
</div>





{% endblock content %}

{% block script_links%}
{% endblock %}
{% block scripts %}
{% endblock %}